Running test: gcd #1... PASS
Running test: f (x) 34... PASS
Running test: f (n) n + 1... PASS
Running test: f (n) g(n-3); g (x) x - 1... PASS
Running test: fact (n) if n = 0 then 1 else n * fac...... PASS
Running test: fib (n) if n < 2 then n else fib (n-1...... PASS
Running test: phi (n) (count ((Î» (k) coprime (k,n))...... ERROR
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: k not found in the environment
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at PdpTestSuite$TestCase.run(PdpTestSuite.java:86)
	at PdpTestSuite.runTests(PdpTestSuite.java:45)
	at PdpPgmTests.main(PdpPgmTests.java:113)
Caused by: java.lang.IllegalArgumentException: k not found in the environment
	at DefaultIdentifierExp.value(DefaultIdentifierExp.java:76)
	at DefaultCallExp.value(DefaultCallExp.java:105)
	at DefaultLambdaExp.value(DefaultLambdaExp.java:88)
	at DefaultCallExp.value(DefaultCallExp.java:105)
	at DefaultCallExp.value(DefaultCallExp.java:89)
	at DefaultLambdaExp.value(DefaultLambdaExp.java:88)
	at DefaultCallExp.value(DefaultCallExp.java:108)
	at Programs.run(Programs.java:42)
	at PdpPgmTests.lambda$addTest$1(PdpPgmTests.java:132)
	at PdpTestSuite$TestCase.lambda$run$0(PdpTestSuite.java:84)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Running test: f (n) g (n);g (f) if f < 2 then i (f)...... FAIL
  actual:   20
  expected: 55
Running test: # Inner product of two vectors.# # Cr...... ERROR
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: i not found in the environment
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at PdpTestSuite$TestCase.run(PdpTestSuite.java:86)
	at PdpTestSuite.runTests(PdpTestSuite.java:45)
	at PdpPgmTests.main(PdpPgmTests.java:113)
Caused by: java.lang.IllegalArgumentException: i not found in the environment
	at DefaultIdentifierExp.value(DefaultIdentifierExp.java:76)
	at DefaultLambdaExp.value(DefaultLambdaExp.java:88)
	at DefaultCallExp.value(DefaultCallExp.java:105)
	at DefaultCallExp.value(DefaultCallExp.java:105)
	at DefaultLambdaExp.value(DefaultLambdaExp.java:88)
	at DefaultCallExp.value(DefaultCallExp.java:108)
	at Programs.run(Programs.java:42)
	at PdpPgmTests.lambda$addTest$1(PdpPgmTests.java:132)
	at PdpTestSuite$TestCase.lambda$run$0(PdpTestSuite.java:84)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Running test: # Inner product of two vectors.# # Cr...... ERROR
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: i not found in the environment
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at PdpTestSuite$TestCase.run(PdpTestSuite.java:86)
	at PdpTestSuite.runTests(PdpTestSuite.java:45)
	at PdpPgmTests.main(PdpPgmTests.java:113)
Caused by: java.lang.IllegalArgumentException: i not found in the environment
	at DefaultIdentifierExp.value(DefaultIdentifierExp.java:76)
	at DefaultLambdaExp.value(DefaultLambdaExp.java:88)
	at DefaultCallExp.value(DefaultCallExp.java:105)
	at DefaultCallExp.value(DefaultCallExp.java:105)
	at DefaultLambdaExp.value(DefaultLambdaExp.java:88)
	at DefaultCallExp.value(DefaultCallExp.java:108)
	at Programs.run(Programs.java:42)
	at PdpPgmTests.lambda$addTest$1(PdpPgmTests.java:132)
	at PdpTestSuite$TestCase.lambda$run$0(PdpTestSuite.java:84)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Running test: # Church numerals## The natural numbe...... ERROR
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: x not found in the environment
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at PdpTestSuite$TestCase.run(PdpTestSuite.java:86)
	at PdpTestSuite.runTests(PdpTestSuite.java:45)
	at PdpPgmTests.main(PdpPgmTests.java:113)
Caused by: java.lang.IllegalArgumentException: x not found in the environment
	at DefaultIdentifierExp.value(DefaultIdentifierExp.java:76)
	at DefaultLambdaExp.value(DefaultLambdaExp.java:88)
	at DefaultLambdaExp.value(DefaultLambdaExp.java:88)
	at DefaultCallExp.value(DefaultCallExp.java:108)
	at DefaultCallExp.value(DefaultCallExp.java:89)
	at DefaultCallExp.value(DefaultCallExp.java:105)
	at DefaultLambdaExp.value(DefaultLambdaExp.java:88)
	at DefaultLambdaExp.value(DefaultLambdaExp.java:88)
	at DefaultLambdaExp.value(DefaultLambdaExp.java:88)
	at DefaultCallExp.value(DefaultCallExp.java:108)
	at DefaultIfExp.value(DefaultIfExp.java:103)
	at DefaultLambdaExp.value(DefaultLambdaExp.java:88)
	at DefaultCallExp.value(DefaultCallExp.java:108)
	at DefaultCallExp.value(DefaultCallExp.java:105)
	at DefaultIfExp.value(DefaultIfExp.java:103)
	at DefaultLambdaExp.value(DefaultLambdaExp.java:88)
	at DefaultCallExp.value(DefaultCallExp.java:108)
	at DefaultCallExp.value(DefaultCallExp.java:105)
	at DefaultIfExp.value(DefaultIfExp.java:103)
	at DefaultLambdaExp.value(DefaultLambdaExp.java:88)
	at DefaultCallExp.value(DefaultCallExp.java:108)
	at DefaultCallExp.value(DefaultCallExp.java:105)
	at DefaultIfExp.value(DefaultIfExp.java:103)
	at DefaultLambdaExp.value(DefaultLambdaExp.java:88)
	at DefaultCallExp.value(DefaultCallExp.java:108)
	at DefaultCallExp.value(DefaultCallExp.java:105)
	at DefaultCallExp.value(DefaultCallExp.java:105)
	at DefaultLambdaExp.value(DefaultLambdaExp.java:88)
	at DefaultCallExp.value(DefaultCallExp.java:108)
	at Programs.run(Programs.java:42)
	at PdpPgmTests.lambda$addTest$1(PdpPgmTests.java:132)
	at PdpTestSuite$TestCase.lambda$run$0(PdpTestSuite.java:84)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Running test: # Church numerals## The natural numbe...... ERROR
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: x not found in the environment
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at PdpTestSuite$TestCase.run(PdpTestSuite.java:86)
	at PdpTestSuite.runTests(PdpTestSuite.java:45)
	at PdpPgmTests.main(PdpPgmTests.java:113)
Caused by: java.lang.IllegalArgumentException: x not found in the environment
	at DefaultIdentifierExp.value(DefaultIdentifierExp.java:76)
	at DefaultLambdaExp.value(DefaultLambdaExp.java:88)
	at DefaultLambdaExp.value(DefaultLambdaExp.java:88)
	at DefaultCallExp.value(DefaultCallExp.java:108)
	at DefaultCallExp.value(DefaultCallExp.java:89)
	at DefaultCallExp.value(DefaultCallExp.java:105)
	at DefaultLambdaExp.value(DefaultLambdaExp.java:88)
	at DefaultLambdaExp.value(DefaultLambdaExp.java:88)
	at DefaultLambdaExp.value(DefaultLambdaExp.java:88)
	at DefaultCallExp.value(DefaultCallExp.java:108)
	at DefaultIfExp.value(DefaultIfExp.java:103)
	at DefaultLambdaExp.value(DefaultLambdaExp.java:88)
	at DefaultCallExp.value(DefaultCallExp.java:108)
	at DefaultCallExp.value(DefaultCallExp.java:105)
	at DefaultIfExp.value(DefaultIfExp.java:103)
	at DefaultLambdaExp.value(DefaultLambdaExp.java:88)
	at DefaultCallExp.value(DefaultCallExp.java:108)
	at DefaultCallExp.value(DefaultCallExp.java:105)
	at DefaultIfExp.value(DefaultIfExp.java:103)
	at DefaultLambdaExp.value(DefaultLambdaExp.java:88)
	at DefaultCallExp.value(DefaultCallExp.java:108)
	at DefaultCallExp.value(DefaultCallExp.java:105)
	at DefaultIfExp.value(DefaultIfExp.java:103)
	at DefaultLambdaExp.value(DefaultLambdaExp.java:88)
	at DefaultCallExp.value(DefaultCallExp.java:108)
	at DefaultCallExp.value(DefaultCallExp.java:105)
	at DefaultIfExp.value(DefaultIfExp.java:103)
	at DefaultLambdaExp.value(DefaultLambdaExp.java:88)
	at DefaultCallExp.value(DefaultCallExp.java:108)
	at DefaultCallExp.value(DefaultCallExp.java:105)
	at DefaultIfExp.value(DefaultIfExp.java:103)
	at DefaultLambdaExp.value(DefaultLambdaExp.java:88)
	at DefaultCallExp.value(DefaultCallExp.java:108)
	at DefaultCallExp.value(DefaultCallExp.java:105)
	at DefaultCallExp.value(DefaultCallExp.java:105)
	at DefaultLambdaExp.value(DefaultLambdaExp.java:88)
	at DefaultCallExp.value(DefaultCallExp.java:108)
	at Programs.run(Programs.java:42)
	at PdpPgmTests.lambda$addTest$1(PdpPgmTests.java:132)
	at PdpTestSuite$TestCase.lambda$run$0(PdpTestSuite.java:84)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Running test: # Given lo and hi, returns the number...... ERROR
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: p not found in the environment
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at PdpTestSuite$TestCase.run(PdpTestSuite.java:86)
	at PdpTestSuite.runTests(PdpTestSuite.java:45)
	at PdpPgmTests.main(PdpPgmTests.java:113)
Caused by: java.lang.IllegalArgumentException: p not found in the environment
	at DefaultIdentifierExp.value(DefaultIdentifierExp.java:76)
	at DefaultCallExp.value(DefaultCallExp.java:105)
	at DefaultLambdaExp.value(DefaultLambdaExp.java:88)
	at DefaultCallExp.value(DefaultCallExp.java:105)
	at DefaultLambdaExp.value(DefaultLambdaExp.java:88)
	at DefaultCallExp.value(DefaultCallExp.java:108)
	at DefaultCallExp.value(DefaultCallExp.java:105)
	at DefaultLambdaExp.value(DefaultLambdaExp.java:88)
	at DefaultCallExp.value(DefaultCallExp.java:108)
	at Programs.run(Programs.java:42)
	at PdpPgmTests.lambda$addTest$1(PdpPgmTests.java:132)
	at PdpTestSuite$TestCase.lambda$run$0(PdpTestSuite.java:84)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Running test: # Given lo and hi, returns the number...... ERROR
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: p not found in the environment
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at PdpTestSuite$TestCase.run(PdpTestSuite.java:86)
	at PdpTestSuite.runTests(PdpTestSuite.java:45)
	at PdpPgmTests.main(PdpPgmTests.java:113)
Caused by: java.lang.IllegalArgumentException: p not found in the environment
	at DefaultIdentifierExp.value(DefaultIdentifierExp.java:76)
	at DefaultCallExp.value(DefaultCallExp.java:105)
	at DefaultLambdaExp.value(DefaultLambdaExp.java:88)
	at DefaultCallExp.value(DefaultCallExp.java:105)
	at DefaultLambdaExp.value(DefaultLambdaExp.java:88)
	at DefaultCallExp.value(DefaultCallExp.java:108)
	at DefaultCallExp.value(DefaultCallExp.java:105)
	at DefaultLambdaExp.value(DefaultLambdaExp.java:88)
	at DefaultCallExp.value(DefaultCallExp.java:108)
	at Programs.run(Programs.java:42)
	at PdpPgmTests.lambda$addTest$1(PdpPgmTests.java:132)
	at PdpTestSuite$TestCase.lambda$run$0(PdpTestSuite.java:84)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Running test: # Binary search tree benchmark.## Cre...... ERROR
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: key not found in the environment
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at PdpTestSuite$TestCase.run(PdpTestSuite.java:86)
	at PdpTestSuite.runTests(PdpTestSuite.java:45)
	at PdpPgmTests.main(PdpPgmTests.java:113)
Caused by: java.lang.IllegalArgumentException: key not found in the environment
	at DefaultIdentifierExp.value(DefaultIdentifierExp.java:76)
	at DefaultCallExp.value(DefaultCallExp.java:105)
	at DefaultCallExp.value(DefaultCallExp.java:105)
	at DefaultLambdaExp.value(DefaultLambdaExp.java:88)
	at DefaultCallExp.value(DefaultCallExp.java:89)
	at DefaultIfExp.value(DefaultIfExp.java:103)
	at DefaultLambdaExp.value(DefaultLambdaExp.java:88)
	at DefaultCallExp.value(DefaultCallExp.java:108)
	at DefaultIfExp.value(DefaultIfExp.java:101)
	at DefaultLambdaExp.value(DefaultLambdaExp.java:88)
	at DefaultCallExp.value(DefaultCallExp.java:108)
	at DefaultCallExp.value(DefaultCallExp.java:105)
	at DefaultLambdaExp.value(DefaultLambdaExp.java:88)
	at DefaultCallExp.value(DefaultCallExp.java:108)
	at Programs.run(Programs.java:42)
	at PdpPgmTests.lambda$addTest$1(PdpPgmTests.java:132)
	at PdpTestSuite$TestCase.lambda$run$0(PdpTestSuite.java:84)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Running test: # Binary search tree benchmark.## Cre...... ERROR
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: key not found in the environment
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at PdpTestSuite$TestCase.run(PdpTestSuite.java:86)
	at PdpTestSuite.runTests(PdpTestSuite.java:45)
	at PdpPgmTests.main(PdpPgmTests.java:113)
Caused by: java.lang.IllegalArgumentException: key not found in the environment
	at DefaultIdentifierExp.value(DefaultIdentifierExp.java:76)
	at DefaultCallExp.value(DefaultCallExp.java:105)
	at DefaultCallExp.value(DefaultCallExp.java:105)
	at DefaultLambdaExp.value(DefaultLambdaExp.java:88)
	at DefaultCallExp.value(DefaultCallExp.java:89)
	at DefaultIfExp.value(DefaultIfExp.java:103)
	at DefaultLambdaExp.value(DefaultLambdaExp.java:88)
	at DefaultCallExp.value(DefaultCallExp.java:108)
	at DefaultIfExp.value(DefaultIfExp.java:101)
	at DefaultLambdaExp.value(DefaultLambdaExp.java:88)
	at DefaultCallExp.value(DefaultCallExp.java:108)
	at DefaultCallExp.value(DefaultCallExp.java:105)
	at DefaultLambdaExp.value(DefaultLambdaExp.java:88)
	at DefaultCallExp.value(DefaultCallExp.java:108)
	at Programs.run(Programs.java:42)
	at PdpPgmTests.lambda$addTest$1(PdpPgmTests.java:132)
	at PdpTestSuite$TestCase.lambda$run$0(PdpTestSuite.java:84)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
6 success(es) 1 failure(s) 9 error(s) 16 test(s) run